### PR TITLE
Feature/readme sample cleanup

### LINKED ISSUE #5: Example Not Functional
Example is not functional :-1:

### PR DESCRIPTION
**Pull request by pnovotnak**
Ok, here's all I can do. I'm brand new to go (connecting to FTP was my first project) so it should probably be reviewed before merge.

I think it fixes #5

### CODE REVIEW

**Comment by MikhailKlemin** [comment]
Hi there is error in sample:

```
 config := tls.Config{
            InsecureSkipVerify: true,
            ClientAuth:         tls.RequestClientCert,
        }
```

I guess should be

```
>  config := &tls.Config{
>             InsecureSkipVerify: true,
>             ClientAuth:         tls.RequestClientCert,
>         }
```

Will not compile otherwised.

**Comment by pnovotnak** [comment]
Example fixed, plus updated from master

**Comment by nl5887** [comment]
Great work! Thx.

**Comment by captainbuckkets** [comment]
This is not reflected in the current README

**Pull request merged**
